---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Copy nftables configuration (for public IdP mode)
#
- name: Copy nftables configuration (for public IdP mode)
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /etc/nftables.conf
    src: nftables-public.conf
    force: yes
  when: project_idp_mode == "public"


# Copy nftables configuration (for gitea IdP mode)
#
- name: Copy nftables configuration (for gitea IdP mode)
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /etc/nftables.conf
    src: nftables-gitea.conf
    force: yes
  when: project_idp_mode == "gitea"
