---
- name: Provision hugo-website-webserver container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Project configuration
    - "{{ playbook_dir }}/../../configuration/configuration_{{ host_id }}.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-consul
    - role: install-nginx
    - role: install-oauth2-proxy
    - role: set-up-firewall
    - role: set-up-consul
    - role: set-up-webserver
    - role: set-up-oauth2-proxy
