---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Provision hugo-website-provisioner container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Project configuration
    - "{{ playbook_dir }}/../../configuration/configuration_{{ host_id }}.yml"

  roles:
    - role: upgrade-container
    - role: install-nftables
    - role: install-rsyslog
    - role: install-consul
    - role: install-git
    - role: install-rsync
    - role: install-webhook
    - role: install-hugo
    - role: set-up-firewall-provisioner
    - role: set-up-consul
    - role: set-up-website-provisioner
    - role: set-up-webhook
