---

# Copy iptables rules script (for public IdP mode)
#
- name: Copy firewall rules script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/iptables-rules.sh
    src: iptables-rules-public.sh
    force: yes
  when: project_idp_mode == "public"


# Copy iptables rules script (for gitea IdP mode)
#
- name: Copy firewall rules script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/iptables-rules.sh
    src: iptables-rules-gitea.sh
    force: yes
  when: project_idp_mode == "gitea"


# Copy firewall service definition
#
- name: Copy firewall service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/iptables-rules.service
    src: iptables-rules.service
    force: yes


# Enable iptables rules service
#
- name: Enable firewall service
  service:
    name: iptables-rules.service
    enabled: yes
    state: started
